sudo: required
services:
  - docker

before_install:
  - docker build -t panfio/ci -f ./client/Dockerfile.dev ./client

script:
  - docker run panfio/ci npm run test -- --coverage

after_success:
  - docker build -t panfio/ci-client ./client
  - docker build -t panfio/ci-nginx ./nginx
  - docker build -t panfio/ci-server ./server
  - docker build -t panfio/ci-worker ./worker
  - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push panfio/ci-client
  - docker push panfio/ci-nginx
  - docker push panfio/ci-server
  - docker push panfio/ci-worker
#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "App name"
#  env: "env name"
#  bucket-name: "07-09 ba bla bla"
#  bucket-path: "App name"
#  on:
#    branch: master
